"""
WorldGen URDF Generator
=======================
Converts exported .obj meshes into physically grounded URDF files.

Key research contribution:
  - Automatically computes mass-normalized inertia tensors from mesh volume
  - Uses trimesh for accurate centroid and principal-axis computation
  - Separates visual mesh (high-res) from collision mesh (low-res)
  - All inertial parameters follow SI units (kg, m, kg m2)

Usage:
  python3 02_generate_urdfs.py --objects_dir ./objects --urdfs_dir ./urdfs

Reference for inertia computation:
  Blow, J. "How to find the inertia tensor of a complex shape", 2004.
"""

import os
import argparse
import json
import numpy as np

try:
    import trimesh
except ImportError:
    print("ERROR: trimesh not found. Run: pip3 install trimesh")
    exit(1)


# ── Physical properties for each object  ─────────────────────────────────────
# (density in kg/m³, chosen to match real-world analogs)

OBJECT_PROPERTIES = {
    "sphere":     {"density": 1100,  "material": "rubber",    "restitution": 0.7, "friction": 0.8},
    "bevel_box":  {"density": 700,   "material": "wood",      "restitution": 0.3, "friction": 0.6},
    "l_bracket":  {"density": 2700,  "material": "aluminum",  "restitution": 0.2, "friction": 0.5},
}


# ── Inertia computation ───────────────────────────────────────────────────────

def compute_inertial(mesh_path: str, density: float):
    """
    Load a mesh and compute:
      - volume  (m³)
      - mass    (kg) = density × volume
      - center of mass  (3-vector, m)
      - inertia tensor  (3×3 matrix, kg m2) in the body's own frame,
        expressed at the center of mass

    Returns a dict with keys: mass, com, inertia_matrix
    """
    mesh = trimesh.load(mesh_path, force='mesh')

    if not mesh.is_watertight:
        print(f"  [WARN] {os.path.basename(mesh_path)} is not watertight — "
              "inertia estimate may be inaccurate. Convex hull used as fallback.")
        mesh = mesh.convex_hull

    volume   = mesh.volume                    # m³
    mass     = density * volume               # kg
    com      = mesh.center_mass               # (3,) in mesh coords

    # Inertia tensor at centroid (trimesh returns it already at CoM)
    I_raw    = mesh.moment_inertia            # (3,3) kg/m³ · m⁵ = kg m2 (unnorm.)
    I_tensor = density * I_raw               # scale by density to get kg m2

    return {
        "mass":            float(mass),
        "com":             com.tolist(),
        "inertia_matrix":  I_tensor.tolist(),
    }


# ── URDF writer ───────────────────────────────────────────────────────────────

URDF_TEMPLATE = """\
<?xml version="1.0" ?>
<!--
  Auto-generated by WorldGen URDF Generator
  Object : {name}
  Material: {material}
  Mass    : {mass:.4f} kg
  Density : {density} kg/m³
  CoM     : {com}
-->
<robot name="{name}">

  <link name="base_link">

    <!-- ── Visual geometry (high-resolution) ── -->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{visual_mesh}" scale="1 1 1"/>
      </geometry>
      <material name="{material}">
        <color rgba="{color}"/>
      </material>
    </visual>

    <!-- ── Collision geometry (low-res for solver speed) ── -->
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{collision_mesh}" scale="1 1 1"/>
      </geometry>
    </collision>

    <!-- ── Inertial parameters (computed from mesh volume + density) ── -->
    <inertial>
      <origin xyz="{com_x:.6f} {com_y:.6f} {com_z:.6f}" rpy="0 0 0"/>
      <mass value="{mass:.6f}"/>
      <inertia
        ixx="{ixx:.8f}" ixy="{ixy:.8f}" ixz="{ixz:.8f}"
        iyy="{iyy:.8f}" iyz="{iyz:.8f}"
        izz="{izz:.8f}"/>
    </inertial>

  </link>

  <!-- ── Contact dynamics parameters (PyBullet joint dynamics) ── -->
  <!-- Set via pybullet.changeDynamics() in simulation script     -->
  <!-- restitution={restitution},  lateralFriction={friction}     -->

</robot>
"""

MATERIAL_COLORS = {
    "rubber":   "0.15 0.15 0.15 1.0",
    "wood":     "0.72 0.53 0.33 1.0",
    "aluminum": "0.75 0.75 0.80 1.0",
}


def write_urdf(name, props, inertial, objects_dir, urdfs_dir):
    I  = np.array(inertial["inertia_matrix"])
    com = inertial["com"]

    urdf_content = URDF_TEMPLATE.format(
        name           = name,
        material       = props["material"],
        density        = props["density"],
        mass           = inertial["mass"],
        com            = [f"{v:.4f}" for v in com],
        visual_mesh    = os.path.abspath(os.path.join(objects_dir, f"{name}.obj")),
        collision_mesh = os.path.abspath(os.path.join(objects_dir, f"{name}_col.obj")),
        color          = MATERIAL_COLORS[props["material"]],
        com_x=com[0], com_y=com[1], com_z=com[2],
        ixx=I[0,0], ixy=I[0,1], ixz=I[0,2],
        iyy=I[1,1], iyz=I[1,2],
        izz=I[2,2],
        restitution    = props["restitution"],
        friction       = props["friction"],
    )

    out_path = os.path.join(urdfs_dir, f"{name}.urdf")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(urdf_content)
    return out_path


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="WorldGen URDF Generator")
    parser.add_argument("--objects_dir", default="./objects")
    parser.add_argument("--urdfs_dir",   default="./urdfs")
    args = parser.parse_args()

    os.makedirs(args.urdfs_dir, exist_ok=True)
    summary = {}

    for name, props in OBJECT_PROPERTIES.items():
        vis_mesh = os.path.join(args.objects_dir, f"{name}.obj")
        col_mesh = os.path.join(args.objects_dir, f"{name}_col.obj")

        if not os.path.exists(vis_mesh):
            print(f"[SKIP] {name}: {vis_mesh} not found")
            continue

        print(f"\n[Processing] {name}")
        inertial = compute_inertial(vis_mesh, props["density"])

        print(f"  mass   = {inertial['mass']:.4f} kg")
        print(f"  CoM    = {[f'{v:.4f}' for v in inertial['com']]}")
        I = np.array(inertial["inertia_matrix"])
        print(f"  Ixx    = {I[0,0]:.6e}  Iyy={I[1,1]:.6e}  Izz={I[2,2]:.6e}")
        print(f"  Ixy    = {I[0,1]:.6e}  Ixz={I[0,2]:.6e}  Iyz={I[1,2]:.6e}")

        urdf_path = write_urdf(name, props, inertial, args.objects_dir, args.urdfs_dir)
        print(f"  → URDF: {urdf_path}")

        summary[name] = {
            "urdf": urdf_path,
            "mass_kg": inertial["mass"],
            "material": props["material"],
        }

    # Save summary JSON
    summary_path = os.path.join(args.urdfs_dir, "objects_summary.json")
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"\n[Done] Summary saved to {summary_path}")


if __name__ == "__main__":
    main()
